sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.*

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/phpspec run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
