language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*
  - SYMFONY_VERSION=4.2.*

matrix:
  fast_finish: true
  exclude:
    - php: 7.0
      env: SYMFONY_VERSION=4.0.*
    - php: 7.0
      env: SYMFONY_VERSION=4.1.*
    - php: 7.0
      env: SYMFONY_VERSION=4.2.*

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
