services:
  tree_house.worker.queue_manager:
    public: true
    class: TreeHouse\WorkerBundle\QueueManager
    arguments:
      - ~ # injected in extension
      - '@event_dispatcher'
      - '@logger'
    tags:
      - { name: monolog.logger, channel: worker }

  tree_house.worker.command.clear:
    class: TreeHouse\WorkerBundle\Command\ClearCommand
    arguments:
      - '@tree_house.worker.queue_manager'
    tags:
      - { name: console.command }

  tree_house.worker.command.execute:
    class: TreeHouse\WorkerBundle\Command\ExecuteCommand
    arguments:
      - '@tree_house.worker.queue_manager'
    tags:
      - { name: console.command }

  tree_house.worker.command.inspect:
    class: TreeHouse\WorkerBundle\Command\InspectCommand
    arguments:
      - '@tree_house.worker.queue_manager'
    tags:
      - { name: console.command }

  tree_house.worker.command.kick:
    class: TreeHouse\WorkerBundle\Command\KickCommand
    arguments:
      - '@tree_house.worker.queue_manager'
    tags:
      - { name: console.command }

  tree_house.worker.command.peek:
    class: TreeHouse\WorkerBundle\Command\PeekCommand
    arguments:
      - '@tree_house.worker.queue_manager'
    tags:
      - { name: console.command }

  tree_house.worker.command.list:
    class: TreeHouse\WorkerBundle\Command\ListCommand
    arguments:
      - '@tree_house.worker.queue_manager'
    tags:
      - { name: console.command }

  tree_house.worker.command.run:
    class: TreeHouse\WorkerBundle\Command\RunCommand
    arguments:
      - '@tree_house.worker.queue_manager'
    tags:
      - { name: console.command }

  tree_house.worker.command.schedule:
    class: TreeHouse\WorkerBundle\Command\ScheduleCommand
    arguments:
      - '@tree_house.worker.queue_manager'
    calls:
      - ['setDoctrine', ['@?doctrine']]
    tags:
      - { name: console.command }
